### ISSUE TITLE
LFM 准确率很低

### ISSUE THREAD

**Issue by 312shan** [fuxuemingzhu/MovieLens-Recommender#3]
LFM 速度确实快了，准确率等四个指标却很低，还没有 random 好
precision=0.0038	recall=0.0023	coverage=0.0046	popularity=3.7217
模型显然没学到东西。

**Comment by fuxuemingzhu** [comment]
据之前的测试，LFM的效果和向量的随机值初始化有关，这里存疑，暂时没有时间解决。

**Comment by 312shan** [comment]
LFM 做如下修改可以显著提高模型效果：

```
lamb = 0.001
alpha = 0.015
self.P[user] = np.random.normal(0, .1, (K,))
self.Q[item] = np.random.normal(0, .1, (K,))
# self.alpha *= 0.9 不做学习率衰减
```

ml-100k 的成绩是：
precision=0.1879	recall=0.1765	coverage=0.2519	popularity=5.3150

**Comment by zhuzigege** [comment]
把epoch提高就行，我设置为50的效果

precision=0.2169	recall=0.2037	coverage=0.2711	popularity=5.3573

**Comment by fuxuemingzhu** [comment]
主干代码已经增加了LFM的epoch为20，效果正常了。
